name:                H6502
version:             0.1.0.0
github:              "damiik/H6502"
license:             BSD-3-Clause
author:              "Dariusz Mikołajczyk"
maintainer:          "damii@poczta.onet.pl"
copyright:           "2025 Dariusz Mikołajczyk"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/damiik/H6502#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- containers
- transformers
- text
- split # Added for Data.List.Split
- optparse-applicative # Added for command-line options
- bytestring # Added for ByteString support
- binary
- filepath
- vector
- primitive
- deepseq


ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
  - Lib
  - Assembly
  - Assembly.Core   # Add the new Core module
  - Assembly.EDSLInstr # reexported by Assembly
  - Assembly.Memory
  - Assembly.ArithmeticLogic
  - Assembly.ControlFlow
  - Assembly.Macros
  - Assembly.List
  - C64
  - C64.Examples
  - C64.SerialPort
  - C64.HelpersC64
  - MOS6502Emulator
  - MOS6502Emulator.Machine
  - MOS6502Emulator.Registers
  - MOS6502Emulator.Memory
  - MOS6502Emulator.Instructions
  - MOS6502Emulator.Debugger
  - MOS6502Emulator.DissAssembler
  - MOS6502Emulator.Core
  - MOS6502Emulator.Debugger.VimMode
  other-modules:
  - C64.HelloWorld  # reexported by C64.Examples
  - C64.HorizontalBars # reexported by C64.Examples
  - Assembly.Branch  # reexported by Assembly
  - Assembly.Instructions6502 # reexported by Assembly

executables:
  H6502-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - H6502
    # Add dependencies needed by Assembly here if they weren't top-level
    # - mtl
    # - containers

tests:
  H6502-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - H6502
    - hspec
